databases:
  - name: yourcomic_DB
    databaseName: yourcomic_db
    user: yourcomic
    region: singapore

services:
  - type: web
    name: yourcomic
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yourcomic_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
